import Head from "next/head";
import InnerContext from "../Context";
import {
  Conatct,
  Footer,
  Header,
  Main,
  Price,
  Process,
  Protfolio,
  Service,
  Testimonial,
} from "../Components";
export default function Home() {
  return (
    <InnerContext>
      <Head>
        <title>Nu Terra Labs</title>
        <meta name="description" content="Generated by Nu Terra Labs" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=family=Fira+Sans:ital,wght@0,100;1,100&family=Libre+Bodoni:wght@700&family=Quantico:ital,wght@0,400;0,700;1,700&family=Roboto:ital,wght@1,900&family=Water+Brush&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Header />
        <Main />
      </div>
      <Service />
      <Process />
      <Protfolio />
      <Conatct />
      <Testimonial />
      <div className="bg-gray-900">
        <Price />
        <Footer />
      </div>
    </InnerContext>
  );
}
