import Head from "next/head";
import Script from "next/script";
import InnerContext from "../Context";
import {
  Conatct,
  Footer,
  Header,
  Main,
  Price,
  Process,
  Protfolio,
  Service,
  Testimonial,
} from "../Components";

export default function Home() {
  return (
    <InnerContext>
      <Head>
        <title>Nu Terra Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
  
      <body>
  
        <div>
          <Header />
          <Main />
        </div>
        <Service />
        <Process />
        <Protfolio />
        <Conatct />
        {/* <Testimonial /> */}
        <Price />
        <div className="">
          <Footer />
        </div>
      </body>
    </InnerContext>
  );
}
